// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 29vNMWd6gz8N9ALUqwUWht
// Component: dOddoL9RPC4
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: PNlHKnwGUdd/component
import { SupabaseQuery } from "../../CodeComponents/DatabaseComponents"; // plasmic-import: Ep7SWTTde6y/codeComponent
import { SupabaseGridCollection } from "../../CodeComponents/DisplayCollections"; // plasmic-import: Lz1vU9pW3M6C/codeComponent
import Post from "../../Post"; // plasmic-import: jHuN7BO9jYv/component
import { SupabaseTextField } from "../../CodeComponents/DisplayCollections"; // plasmic-import: qfhrRSTHm0PM/codeComponent
import { SupabaseImgField } from "../../CodeComponents/DisplayCollections"; // plasmic-import: Aj6z3gH4zG3Q/codeComponent
import { SupabaseTableCollection } from "../../CodeComponents/DisplayCollections"; // plasmic-import: fzdZdG-Pi4U-/codeComponent

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_copy_of_copy_of_supabase.module.css"; // plasmic-import: 29vNMWd6gz8N9ALUqwUWht/projectcss
import sty from "./PlasmicPosts.module.css"; // plasmic-import: dOddoL9RPC4/css

import PlusIcon from "./icons/PlasmicIcon__Plus"; // plasmic-import: aYaxqvNKCLAw/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: 8Mx7VG07ecTo/icon

export type PlasmicPosts__VariantMembers = {};

export type PlasmicPosts__VariantsArgs = {};
type VariantPropType = keyof PlasmicPosts__VariantsArgs;
export const PlasmicPosts__VariantProps = new Array<VariantPropType>();

export type PlasmicPosts__ArgsType = {};
type ArgPropType = keyof PlasmicPosts__ArgsType;
export const PlasmicPosts__ArgProps = new Array<ArgPropType>();

export type PlasmicPosts__OverridesType = {
  root?: p.Flex<"div">;
  h2?: p.Flex<"h2">;
  freeBox?: p.Flex<"div">;
  button?: p.Flex<typeof Button>;
  svg?: p.Flex<"svg">;
  post?: p.Flex<typeof Post>;
  supabaseImgField?: p.Flex<typeof SupabaseImgField>;
  img?: p.Flex<typeof p.PlasmicImg>;
  supabaseTableCollection?: p.Flex<typeof SupabaseTableCollection>;
};

export interface DefaultPostsProps {
  className?: string;
}

function PlasmicPosts__RenderFunc(props: {
  variants: PlasmicPosts__VariantsArgs;
  args: PlasmicPosts__ArgsType;
  overrides: PlasmicPosts__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__dEjvr
        )}
      >
        <React.Fragment>
          <React.Fragment>{""}</React.Fragment>
          <h2
            data-plasmic-name={"h2"}
            data-plasmic-override={overrides.h2}
            className={classNames(
              projectcss.all,
              projectcss.h2,
              projectcss.__wab_text,
              sty.h2
            )}
          >
            {"Posts"}
          </h2>
          <React.Fragment>{""}</React.Fragment>
        </React.Fragment>
      </div>

      {true ? (
        <div
          data-plasmic-name={"freeBox"}
          data-plasmic-override={overrides.freeBox}
          className={classNames(projectcss.all, sty.freeBox)}
        >
          <Button
            data-plasmic-name={"button"}
            data-plasmic-override={overrides.button}
            className={classNames("__wab_instance", sty.button)}
            color={"softSand" as const}
            link={"/post/add" as const}
            showStartIcon={true}
            size={"compact" as const}
            startIcon={
              <PlusIcon
                data-plasmic-name={"svg"}
                data-plasmic-override={overrides.svg}
                className={classNames(projectcss.all, sty.svg)}
                role={"img"}
              />
            }
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__jdyZi
              )}
            >
              {"New Post"}
            </div>
          </Button>
        </div>
      ) : null}

      <SupabaseQuery
        className={classNames("__wab_instance", sty.supabaseQuery__pEazb)}
        columns={"title, content, id, imageUrl" as const}
        tableName={"posts" as const}
      >
        <SupabaseGridCollection
          className={classNames(
            "__wab_instance",
            sty.supabaseGridCollection__vYKb
          )}
          columnGap={50 as const}
          columns={3 as const}
          loading={
            <p.PlasmicImg
              data-plasmic-name={"img"}
              data-plasmic-override={overrides.img}
              alt={""}
              className={classNames(sty.img)}
              displayHeight={"auto" as const}
              displayMaxHeight={"none" as const}
              displayMaxWidth={"100%" as const}
              displayMinHeight={"0" as const}
              displayMinWidth={"0" as const}
              displayWidth={"auto" as const}
              loading={"lazy" as const}
              src={{
                src: "/plasmic/copy_of_copy_of_supabase/images/loadingIconjpeg.gif",
                fullWidth: 800,
                fullHeight: 600,
                aspectRatio: undefined
              }}
            />
          }
          rowGap={30 as const}
          testLoading={false}
        >
          <Post
            data-plasmic-name={"post"}
            data-plasmic-override={overrides.post}
            className={classNames("__wab_instance", sty.post)}
            description={
              <SupabaseTextField
                className={classNames(
                  "__wab_instance",
                  sty.supabaseTextField__rjAl9
                )}
                name={"{{row.content}}" as const}
              />
            }
            image={
              <SupabaseImgField
                data-plasmic-name={"supabaseImgField"}
                data-plasmic-override={overrides.supabaseImgField}
                className={classNames("__wab_instance", sty.supabaseImgField)}
                url={"{{row.imageUrl}}" as const}
              />
            }
            title={
              <SupabaseTextField
                className={classNames(
                  "__wab_instance",
                  sty.supabaseTextField__afo6V
                )}
                name={"{{row.title}}" as const}
              />
            }
          />
        </SupabaseGridCollection>
      </SupabaseQuery>

      <SupabaseQuery
        className={classNames("__wab_instance", sty.supabaseQuery__sTnuv)}
        columns={"title, content" as const}
        tableName={"posts" as const}
      >
        <SupabaseGridCollection
          className={classNames(
            "__wab_instance",
            sty.supabaseGridCollection___3MgTx
          )}
          columnGap={16 as const}
          columns={4 as const}
          loading={"Loading..."}
          rowGap={16 as const}
        >
          {"Placeholder"}
        </SupabaseGridCollection>
      </SupabaseQuery>

      <SupabaseQuery
        className={classNames("__wab_instance", sty.supabaseQuery___8Bmb)}
        columns={"title, content" as const}
        tableName={"posts" as const}
      >
        <SupabaseGridCollection
          className={classNames(
            "__wab_instance",
            sty.supabaseGridCollection___8Cfc3
          )}
          columnGap={16 as const}
          columns={4 as const}
          loading={"Loading..."}
          rowGap={16 as const}
        >
          {"Placeholder"}
        </SupabaseGridCollection>
      </SupabaseQuery>

      <SupabaseQuery
        className={classNames("__wab_instance", sty.supabaseQuery__gaIf)}
        columns={"title, content, imageUrl" as const}
        tableName={"posts" as const}
      >
        <SupabaseTableCollection
          data-plasmic-name={"supabaseTableCollection"}
          data-plasmic-override={overrides.supabaseTableCollection}
          canEdit={false}
          className={classNames("__wab_instance", sty.supabaseTableCollection)}
          columns={"title, content,imageUrl" as const}
          deleteSlot={"Placeholder"}
          editSlot={"Placeholder"}
          loading={"Loading..."}
        />
      </SupabaseQuery>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "h2",
    "freeBox",
    "button",
    "svg",
    "post",
    "supabaseImgField",
    "img",
    "supabaseTableCollection"
  ],
  h2: ["h2"],
  freeBox: ["freeBox", "button", "svg"],
  button: ["button", "svg"],
  svg: ["svg"],
  post: ["post", "supabaseImgField"],
  supabaseImgField: ["supabaseImgField"],
  img: ["img"],
  supabaseTableCollection: ["supabaseTableCollection"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  h2: "h2";
  freeBox: "div";
  button: typeof Button;
  svg: "svg";
  post: typeof Post;
  supabaseImgField: typeof SupabaseImgField;
  img: typeof p.PlasmicImg;
  supabaseTableCollection: typeof SupabaseTableCollection;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPosts__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPosts__VariantsArgs;
    args?: PlasmicPosts__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPosts__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicPosts__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPosts__ArgProps,
      internalVariantPropNames: PlasmicPosts__VariantProps
    });

    return PlasmicPosts__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPosts";
  } else {
    func.displayName = `PlasmicPosts.${nodeName}`;
  }
  return func;
}

export const PlasmicPosts = Object.assign(
  // Top-level PlasmicPosts renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    h2: makeNodeComponent("h2"),
    freeBox: makeNodeComponent("freeBox"),
    button: makeNodeComponent("button"),
    svg: makeNodeComponent("svg"),
    post: makeNodeComponent("post"),
    supabaseImgField: makeNodeComponent("supabaseImgField"),
    img: makeNodeComponent("img"),
    supabaseTableCollection: makeNodeComponent("supabaseTableCollection"),

    // Metadata about props expected for PlasmicPosts
    internalVariantProps: PlasmicPosts__VariantProps,
    internalArgProps: PlasmicPosts__ArgProps
  }
);

export default PlasmicPosts;
/* prettier-ignore-end */
